### ISSUE TITLE
Come up with a short name

### ISSUE THREAD

**Issue by goibon** [Tomorrows-pollen-today/tomorrows-pollen-today#10]
When people add the website to their homescreen on their phone, the browser will currently suggest `Tomorrow's Pollen` which is 17 characters long.
The limit for app names on iOS seems to be somewhere between 11 and 15 depending on the width of the characters.
Right now the name is truncated into `Tomorrrow'sPol...` which doesn't exactly look great.

We need to come up with a proper short name that won't get truncated so we can always look our best on people's devices.

**Comment by altany** [comment]
How about something like "PollenOutlook" (13 chars)?

I am assuming spaces are always stripped?

**Comment by goibon** [comment]
Hello @altany and @lmeikle, thank you so much for your contributions to this repository, we're glad that you're eager to help 👍 
I'm posting replies to your respective pull requests here as I think it will provide a clearer overview if we have a discussion regarding the name here rather than in separate pull requests.
The short name of the app is quite subjective with no code to review per se and as such I think we can hold off pull requests until we have settled on a name we like 💁‍♂️ 

@altany I think `PollenOutlook` (even with a space between the words) strays too much from the full name `Tomorrows Pollen Today`. A side-note is that spaces are *not* stripped so we can still use them for short names.

@lmeikle Good idea using an abbreviation and it does display without truncating.

**Comment by lassevalentini** [comment]
I think abbreviating to tomorrow's is the simplest and will probably result in less confusion. However the all caps TMRW seems a bit aggressive, so how about just using Tmrw's pollen?

**Comment by lmeikle** [comment]
Yup Tmrw's Pollen looks good to me :)

**Comment by goibon** [comment]
@lmeikle Will you update your pr (#12) to use `Tmrw's Pollen`? Then we'll merge it :shipit:

**Comment by lmeikle** [comment]
Ah sorry yes done that now :)

**Comment by goibon** [comment]
Thanks!
