### ISSUE TITLE
Need a logo and Favicon

### ISSUE THREAD

**Issue by goibon** [Tomorrows-pollen-today/tomorrows-pollen-today#5]
The project could really benefit from having a logo that we could use for the site, the repo and even the organization.
This would also be useful for using as favicon for the site as well as image when users save it to their homescreen on their phones.

Know anyone with graphic skills? Send them our way 👍

**Comment by zuuritaly** [comment]
Hello @rahulsom
I'm a graphic designer and I design logos for open source projects.

Usually I ask the following questions to assist me in the creative process:

Do you have something in your mind for the logo?
Do you want something specific for the logo?
What colors do you want in the logo?

With your answers I will design a logo for your project and if you like it you can keep it and used.

Best Regards

Zuur

**Comment by jbeguna04** [comment]
@goibon , I would like to help you from this issue. Please give me more information about the project or the application for the logo output. Thank you in advance!

**Comment by goibon** [comment]
Hey @jbeguna04! Thank you so much for offering to help 😄 
Well the project is a pollen prediction service that can predict future pollen numbers based on weather and previous pollen numbers. Since it's about pollen and the current pollen type being predicted in the early phases of the project is grass I think green should be a prime color and perhaps could be part of the iconography used.
Like I mentioned in this issue it would be nice to have an image that can be used for:
* The [Tomorrows Pollen Today](https://github.com/Tomorrows-pollen-today) organization
* Favicon for [the website](tomorrowspollen.today)
* Homescreen icon when you save the website to your homescreen on a smartphone

Let me know if you have any other questions

**Comment by jbeguna04** [comment]
![pollen](https://user-images.githubusercontent.com/35353768/42559670-526deb86-8527-11e8-8639-acc30732c638.png)

I have two designs here, Just tell me some suggestions.
Feel free to open opinions. Thank you!

**Comment by goibon** [comment]
@jbeguna04 Cool, I quite like the left design with the parallel lines in green and yellow.
Would it it be possible to see it in some other nuances of green and yellow? I'm curious about how it might look in perhaps a brighter green.

**Comment by jbeguna04** [comment]
Sure @goibon, Ill be sending more color combinations asap, for you to choose.

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/42683207-40556192-86bf-11e8-8d89-50bb1d0ba57c.png)

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/42686163-a1c3c98e-86c7-11e8-8197-a9397a817d0e.png)

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/42686329-1e27a75c-86c8-11e8-953f-cc817a6f3e40.png)

**Comment by goibon** [comment]
@jbeguna04 Wow thank you for replying so quickly 😃 
I really like no. 2 of the last set you sent and I think we want to go with that one. 
Thank you so much for doing this, I really appreciate what you're doing here 👏 
Is there any chance of getting it as an `.svg` file? Ideally both the round, rounded square and just the dots.

**Comment by jbeguna04** [comment]
Yes, I can give the SVG for this files, Do you want me to create different sizes for this logos depending of the usage of those.

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/42696149-e6a7d2c6-86e9-11e8-9f7d-e87ce5f9a26d.png)
Here are some logo types too.

**Comment by goibon** [comment]
@jbeguna04 I'm not sure you have to create different sizes of it as the only usages that have well defined sizes (favicon and homescreen icons) will just be generated from the SVG.
The logo types look cool, we might consider using that for the `README` of the repo 👍

**Comment by jbeguna04** [comment]
Would you still be available if i will send it right now?

**Comment by goibon** [comment]
I'm actually heading out soon so I can't provide quick responses sorry, maybe if we're lucky @lassevalentini has time.

**Comment by jbeguna04** [comment]
Thanks @goibon, Just preparing all the files that is needed for the project ang will be sending it asap.

**Comment by jbeguna04** [comment]
https://drive.google.com/open?id=1SWCRedQ5Kasvf2a6wNxVvhNKlJXu39IR

This are the files for the project and it contains:
- Favicons
- Home Screen Icons
- Logo types for Readme Files

**Comment by goibon** [comment]
@jbeguna04 Thank you for the link, I've started adding it to the project but I noticed that the pictures aren't square, nor a PoT resolution. They are slightly off like the `128px.png` is actually 128x129 and `256px.png` is 256x257.
I think the extra pixel is on the left side, is there any chance you could remove that and reupload the images?

**Comment by jbeguna04** [comment]
Sure @goibon , Sorry for that flaws. I had already change the files and you can check it here:
https://drive.google.com/open?id=10H77rvaMUymh4z-hPHYG02zQ1M-OPIuO

**Comment by jbeguna04** [comment]
@goibon, Hello sir, Have you visited the new files for the logos? Just tell me if you have more to add
Thank You!
